name: RyanDay
favicon: null
layout_spectrum: 0.6550337627995759
typography_spectrum: 0.38304893858730793
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.41633095126599073
  lightness: 0.36942867562174797
  saturation: 0.6720967441797256
  rhythmicContrast: 0.8595028517302126
purpose: []
